CREATE TABLE ENTRY (
  ENTRY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  ENTRY_ACCESS_CODE VARCHAR2(128) NOT NULL,
  MOOD_ID INTEGER NOT NULL,

  FOREIGN KEY (MOOD_ID) REFERENCES MOOD (MOOD_ID)
);

CREATE UNIQUE INDEX ENTRY_PK_IDX ON ENTRY (ENTRY_ID);
CREATE UNIQUE INDEX ENTRY_ACCESS_CODE_IDX ON ENTRY (MOOD_ID, ENTRY_ACCESS_CODE);
CREATE INDEX ENTRY_MOOD_FK_IDX ON ENTRY (MOOD_ID);

CREATE TABLE RECORD (
  ENTRY_ID INTEGER NOT NULL,
  RECORD_DATETIME DATETIME NOT NULL,

  RECORD INTEGER NOT NULL,
  COMMENT VARCHAR2(256),

  PRIMARY KEY (ENTRY_ID, RECORD_DATETIME),
  FOREIGN KEY (ENTRY_ID) REFERENCES ENTRY (ENTRY_ID)
);

CREATE UNIQUE INDEX RECORD_PK_IDX ON RECORD (ENTRY_ID, RECORD_DATETIME);
CREATE INDEX RECORD_ENTRY_FK_IDX ON RECORD (ENTRY_ID);

CREATE TABLE MOOD (
  MOOD_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  MOOD_ACCESS_CODE VARCHAR2(128) NOT NULL,

  TITLE VARCHAR2(128) NOT NULL,
  CONTENT VARCHAR2(512)
);

CREATE UNIQUE INDEX MOOD_PK ON MOOD (MOOD_ID);
CREATE UNIQUE INDEX MOOD_ACCESS_CODE_ID_IDX ON MOOD (MOOD_ID, MOOD_ACCESS_CODE);

CREATE TABLE MAIL (
  ENTRY_ID INTEGER NOT NULL,
  EMAIL VARCHAR2(256),

  PRIMARY KEY (ENTRY_ID),
  FOREIGN KEY (ENTRY_ID) REFERENCES ENRTY (ENTRY_ID)
);

CREATE UNIQUE INDEX MAIL_PK ON MAIL (ENTRY_ID);
