---
name: Go build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install protoc
        run: |
          apt-get update && apt-get install gcc-multilib nodejs npm curl unzip -y
          mkdir -p $HOME/protobuf && pushd $HOME/protobuf
          curl -LO 'https://github.com/google/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip'
          unzip protoc-3.11.4-linux-x86_64.zip
          popd
      - name: Build
        run: |
          export PATH=$HOME/.local/bin:$HOME/protobuf/bin:$PATH
          make dev-dependencies
          make
          make cover
          make release
