---
name: Go release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install protoc
        run: |
          apt-get update && apt-get install gcc-multilib nodejs npm curl unzip -y
          mkdir -p $HOME/protobuf && pushd $HOME/protobuf
          curl -LO 'https://github.com/google/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip'
          unzip protoc-3.11.4-linux-x86_64.zip
          popd
      - name: Build
        run: |
          export PATH=$HOME/.local/bin:$HOME/protobuf/bin:$PATH
          make dev-dependencies
          make release
      - uses: softprops/action-gh-release@v1
        with:
          files: "build/mood-tracker-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish to docker hub
        run: |
          make docker
          make docker-deploy
